Implement merge files
line/centraldogma-python pull request #34
Opened 2022-07-26 05:24 UTC by jrhee17

`CentralDogma` has a feature called `mergeFiles` which lets users "merge" files and retrieve the result easily.

https://github.com/line/centraldogma/blob/0c397eb1f5aa99cec586adcf5417464032ce117f/client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogma.java#L247-L269

It might be useful to implement this feature for the python client as well.

2022-07-27 08:48 UTC, ikhoon reviewed
Welcome Python master! 🐍
Left one minor comment.

2022-07-27 08:48 UTC, ikhoon commented on centraldogma/dogma.py
> +    ) -> MergedEntry[T]:
`T` is only bound to the return type which seems not to tell any useful type information.
How about replacing `T` with `Any` type?
```suggestion
    ) -> MergedEntry[Any]:
```

2022-07-27 17:24 UTC, hexoul requested changes
Thanks for the first PR! Please take a look 🙏

2022-07-27 17:24 UTC, hexoul commented on centraldogma/data/merged_entry.py
> +            raise CentralDogmaException(f"paths is unexpectedly empty for json: {json}")
If error handling is hesitated, there is an alternative way not to use `try-except` like below.
```suggestion
        paths = json["paths"] if "paths" in json and type(json["paths"]) is list else None
        if not paths:
            raise CentralDogmaException(f"paths is unexpectedly empty for json: {json}")
```

2022-07-27 17:24 UTC, hexoul commented on centraldogma/data/merged_entry.py
> +    def content(self) -> T:
Can we narrow down the type hint such as `Union[str, dict]`?

2022-07-28 07:08 UTC, jrhee17 commented on centraldogma/dogma.py
> +    ) -> MergedEntry[T]:
Just removed the generic argument altogether 😅 
Although the java api is defined with a generic type, I'm not foreseeing many changes to the merge feature (and I guess we can make a breaking change if necessary)

2022-07-28 07:08 UTC, jrhee17 commented on centraldogma/content_service.py
> +    def merge_files(
Oops 😅  Done 👍

2022-07-28 07:09 UTC, jrhee17 commented on centraldogma/dogma.py
> +            project_name, repo_name, merge_sources, json_paths, revision
Done 👍   Actually `merge_sources` shouldn't be empty, so added a validation

2022-07-28 07:09 UTC, jrhee17 commented on centraldogma/dogma.py
> +        json_paths: List[str] = None,
Done 👍

2022-07-28 07:09 UTC, jrhee17 commented on centraldogma/data/merged_entry.py
> +        :exception EntryNoContentException if the content is ``None``
Done 👍

2022-07-28 07:09 UTC, jrhee17 commented on centraldogma/data/merged_entry.py
> +        Returns the content.
Done 👍

2022-07-28 07:10 UTC, jrhee17 commented on centraldogma/data/merged_entry.py
> +        content = json["content"]
Good point.

Actually to keep this implementation flexible, I guess it's better to just not validate the response. (in symmetry with other implementations).
I've removed the length validation 🙇

2022-07-28 07:11 UTC, jrhee17 commented on centraldogma/data/merged_entry.py
> +            raise CentralDogmaException(f"paths is unexpectedly empty for json: {json}")
https://github.com/line/centraldogma-python/pull/34#discussion_r931858272 <- Addressed here

2022-07-28 07:11 UTC, jrhee17 commented on centraldogma/data/merged_entry.py
> +    def from_dict(json: Any):
Thanks! Done 👍

2022-07-28 07:11 UTC, jrhee17 commented on centraldogma/data/merged_entry.py
> +    def content(self) -> T:
Thanks! Done 👍

2022-07-30 04:19 UTC, hexoul approved these changes
Mostly LGTM. Thanks a lot @jrhee17 🎊! Please check minor comments for documentation.

2022-07-30 04:19 UTC, hexoul commented on centraldogma/dogma.py
> +
Could you add [`ValueError`](https://github.com/line/centraldogma-python/pull/34/files#diff-c0cbe9e6e370518d8302068abd5cc76c7b27c06d5352372f2ffdf5810f03a17eR154) here?
```suggestion

    :raises ValueError: ...
```

2022-07-30 04:19 UTC, hexoul commented on centraldogma/dogma.py
> +        Returns the merged result of files represented by ``MergeSource``. Each ``MergeSource``
```suggestion
        """Returns the merged result of files represented by ``MergeSource``. Each ``MergeSource``
```

2022-08-01 07:40 UTC, jrhee17 commented on centraldogma/dogma.py
> +
Oh I missed this 😅  Thanks!

2022-08-02 08:53 UTC, ikhoon approved these changes
Thanks, @jrhee17 and @hexoul 🙇‍♂️

2022-08-02 08:53 UTC, merged